/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */
import { createClient } from "@supabase/supabase-js";

export const projectId = "zsbdfdpmyhescdjgczwz";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzYmRmZHBteWhlc2Nkamdjend6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMjYxNTQsImV4cCI6MjA3NjgwMjE1NH0.oJjDHnUzdF0l9bntLdANYPyj3AhxK-M50LDZJo417vA"; // keep the full key

// Build URL and create client so other files can import `supabase`
const supabaseUrl = `https://${projectId}.supabase.co`;
export const supabase = createClient(supabaseUrl, publicAnonKey);

